export { default as Home } from "./home"
export { default as NotFound } from "./not_found"
export { default as RegisterForm } from "./register"
export { default as Login } from "./login"
export { default as SettingsForm } from "./settings/"